
micronaut:
  server:
    port:8080
  application:
    name: clientScylla3
cassandra:
  default:
    basic:
      contact-points:
        - 127.0.0.2:9042
      session-keyspace: clube
      load-balancing-policy:
        local-datacenter: datacenter1


consul:
  client:
    registration:
      check:
        http: true


endpoints:
  health:
    details-visible: ANONYMOUS